version: "3.8"

services:
    app:
        image: ghcr.io/dandikurnia/webportofolio:latest
        container_name: webportofolio-app
        restart: unless-stopped
        ports:
            - "8080:80"
        env_file:
            - .env
        volumes:
            - ./storage:/var/www/html/storage
        networks:
            - app_net

networks:
    app_net:
        external: true
